---
- name: Ensure Fedora/Korora package dependencies
  include: darwin.yml
  when: ansible_distribution == 'MacOSX'

- name: Ensure Ubuntu package dependencies
  include: ubuntu.yml
  when: ( ansible_distribution == 'Ubuntu') or ( ansible_distribution == 'Debian' )

- name: Cloning  oh-my-zsh
  git:
    accept_hostkey: yes
    repo: https://github.com/robbyrussell/oh-my-zsh
    dest: "{{ current_user_home }}/.oh-my-zsh"
  sudo: no