---
 - name: Add spotify key
   apt_key: id=BBEBDCB318AD50EC6865090613B00F1FD2C19886 keyserver="hkp://keyserver.ubuntu.com:80" state=present
   become: yes

 - name: Add spotify repository
   apt_repository: repo="deb http://repository.spotify.com stable non-free"
   become: yes

 - name: Ensure spotify is installed
   apt: name=spotify-client  state=latest
   become: yes
