---
 - name: Add spotify key
   apt_key: id=0DF731E45CE24F27EEEB1450EFDC8610341D9410 keyserver="hkp://keyserver.ubuntu.com:80" state=present
   become: yes

 - name: Add spotify repository
   apt_repository: repo="deb http://repository.spotify.com stable non-free"
   become: yes

 - name: Ensure spotify is installed
   apt: name=spotify-client  state=latest
   become: yes
