---
- name: Ensure required packages
  apt:
    name: "{{ item }}"
    state: latest
  become: yes
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common

- name: Add apt-key for Docker
  apt_key:
    state: present
    #keyserver: hkp://ha.pool.sks-keyservers.net:80
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
  become: yes

- name: Add docker.list to apt-sources
  lineinfile:
    state: present
    create: yes
    dest: /etc/apt/sources.list.d/docker.list
    #line: deb https://apt.dockerproject.org/repo ubuntu-xenial main
    line: deb https://download.docker.com/linux/ubuntu bionic stable
  register: docker_apt
  become: yes

- name: Update apt cache
  apt:
    update_cache: yes
  when: docker_apt.changed
  become: yes

- name: Install docker-ce packages
  apt:
    state: latest
    name: "{{ item }}"
  with_items:
    - docker-ce
    - docker-ce-cli
    - containerd.io
  become: yes
  tags: ["docker","packages"]

#- name: Install docker-engine
#  apt:
#    state: latest
#    name: docker-engine
#  become: yes

- name: Enable and start docker service
  service:
    state: started
    enabled: yes
    name: docker
  become: yes

