---

- name: Configure the APT key
  apt_key:
    url: http://download.opensuse.org/repositories/home:Horst3180/xUbuntu_16.04/Release.key
    state: present
  become: yes
  tags: gnome-themes

- name: Configure the Arc APT repositories
  apt_repository:
    repo: "deb http://download.opensuse.org/repositories/home:/Horst3180/xUbuntu_16.04/ /"
    state: present
  become: yes
  tags: gnome-themes

- name: Install Arc Theme
  apt:
    update_cache: yes
    name: arc-theme
    state: latest
  become: yes
  tags: ["gnome-themes","packages"]


