---

- name: Configure the APT key
  apt_key:
    url: http://download.opensuse.org/repositories/home:Horst3180/xUbuntu_16.04/Release.key
    state: present
  become: yes
  tags: gnome-themes
  when: ansible_distribution_version == "16.04"

- name: Configure the Arc APT repositories
  apt_repository:
    repo: "deb http://download.opensuse.org/repositories/home:/Horst3180/xUbuntu_16.04/ /"
    state: present
  become: yes
  tags: gnome-themes
  when: ansible_distribution_version == "16.04"

- name: Install Arc Theme
  apt:
    update_cache: yes
    name: arc-theme
    state: latest
  become: yes
  tags: ["gnome-themes","packages"]

- name: Configure Numix PPA repo
  apt_repository:
    repo: ppa:numix/ppa
    state: present
  become: yes
  tags: gnome-themes

- name: Install Numix Theme and Icon Sets
  apt:
    update_cache: yes
    name: numix-icon-theme-circle
    state: latest
  become: yes
  tags: ["gnome-themes","packages"]