---
# VirtualBox
- name: Install dkms
  apt:
    name: dkms
    state: latest
  become: yes
  tags: ["virtualbox","packages"]

- name: Configure the Oracle APT key
  apt_key:
    url: https://www.virtualbox.org/download/oracle_vbox.asc
    state: present
  become: yes
  tags: virtualbox

- name: Ensure keys validate (hack)
  apt_key: id=A2F683C52980AECF keyserver="hkp://keyserver.ubuntu.com:80" state=present
  become: yes

- name: Configure the VirtualBox APT repositories
  apt_repository:
    repo: "deb http://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib"
    state: present
  become: yes
  tags: virtualbox

- name: Install virtualbox
  apt:
    update_cache: yes
    name: virtualbox-{{ virtualbox_version }}
    state: present
  become: yes
  tags: ["virtualbox","packages"]

# Install extension pack as well

#- name: Install VBox Guest Additions ISO
#  apt:
#    update_cache: yes
#    name: virtualbox-guest-additions-iso
#    state: latest
#  become: yes
#  tags: ["virtualbox","packages"]
